######################################################################
# Automatically generated by qmake (3.1) Mon Feb 10 16:33:31 2020
######################################################################

TEMPLATE = app
TARGET = qmake
INCLUDEPATH += .

# Input
SOURCES += qmake.cpp

QT += widgets gui
